# Generated by Django 5.2.7 on 2025-10-04 12:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Ville",
                "verbose_name_plural": "Villes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=3, unique=True)),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identifiant unique pour URLs", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom court")),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nom complet"),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Année de fondation",
                    ),
                ),
                ("slogan", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(verbose_name="Description")),
                ("vision", models.TextField(verbose_name="Vision")),
                ("address", models.CharField(max_length=255, verbose_name="Adresse")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Site web"),
                ),
                (
                    "members_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de membres"
                    ),
                ),
                (
                    "leaders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de leaders"
                    ),
                ),
                (
                    "weekly_services_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Services hebdomadaires"
                    ),
                ),
                (
                    "baptisms_current_year",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Baptêmes année courante"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communities",
                        to="communities.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communauté",
                "verbose_name_plural": "Communautés",
                "ordering": ["founded_year", "name"],
            },
        ),
        migrations.CreateModel(
            name="BaptismRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement",
                    models.CharField(max_length=255, verbose_name="Exigence"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baptism_requirements",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exigence de baptême",
                "verbose_name_plural": "Exigences de baptême",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="communities.country",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("spiritual", "Spirituel"),
                            ("sacrament", "Sacrement"),
                            ("formation", "Formation"),
                            ("cultural", "Culturel"),
                            ("social", "Social"),
                            ("evangelization", "Évangélisation"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200, verbose_name="Lieu")),
                (
                    "organizer",
                    models.CharField(max_length=100, verbose_name="Organisateur"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Récurrent"),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("registration_required", models.BooleanField(default=False)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="galleries/"),
                ),
                ("cover_image_url", models.URLField(blank=True, null=True)),
                (
                    "images_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'images"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Publique"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galleries",
                        to="communities.community",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galleries",
                        to="communities.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galerie",
                "verbose_name_plural": "Galeries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery_images/")),
                ("image_url", models.URLField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="communities.gallery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de galerie",
                "verbose_name_plural": "Images de galerie",
                "ordering": ["order", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("position", models.CharField(max_length=100, verbose_name="Position")),
                (
                    "experience_years",
                    models.PositiveIntegerField(verbose_name="Années d'expérience"),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaders",
                        to="communities.community",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leader",
                "verbose_name_plural": "Leaders",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="BibleStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("schedule", models.CharField(max_length=100, verbose_name="Horaire")),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(verbose_name="Durée en semaines"),
                ),
                (
                    "participants_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de participants"
                    ),
                ),
                ("description", models.TextField()),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="En cours"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_studies",
                        to="communities.community",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bible_studies_taught",
                        to="communities.leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étude biblique",
                "verbose_name_plural": "Études bibliques",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Baptism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Date")),
                ("time", models.TimeField(verbose_name="Heure")),
                ("location", models.CharField(max_length=200, verbose_name="Lieu")),
                (
                    "candidates_count",
                    models.PositiveIntegerField(verbose_name="Nombre de candidats"),
                ),
                (
                    "preparation_sessions",
                    models.PositiveIntegerField(verbose_name="Sessions de préparation"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Effectué"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baptisms",
                        to="communities.community",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baptisms_coordinated",
                        to="communities.leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baptême",
                "verbose_name_plural": "Baptêmes",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="LeaderSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Spécialité")),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialties",
                        to="communities.leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spécialité de leader",
                "verbose_name_plural": "Spécialités de leader",
            },
        ),
        migrations.CreateModel(
            name="Meditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "bible_verse",
                    models.CharField(max_length=100, verbose_name="Verset biblique"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("daily", "Méditation quotidienne"),
                            ("weekly", "Réflexion hebdomadaire"),
                            ("youth", "Méditation jeunesse"),
                            ("community", "Méditation communautaire"),
                            ("professional", "Méditation professionnelle"),
                            ("artistic", "Méditation artistique"),
                            ("student", "Méditation étudiante"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("encouragement", "Encouragement"),
                            ("christian_life", "Vie chrétienne"),
                            ("relationships", "Relations"),
                            ("community", "Communauté"),
                            ("creativity", "Créativité"),
                            ("work", "Travail"),
                            ("wisdom", "Sagesse"),
                            ("faith", "Foi"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="Durée (minutes)"),
                ),
                ("published_date", models.DateField(default=django.utils.timezone.now)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meditations",
                        to="communities.leader",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meditations",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "Méditation",
                "verbose_name_plural": "Méditations",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("join_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "baptism",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="communities.baptism",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="communities.community",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("description", models.TextField()),
                (
                    "participants_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de participants"
                    ),
                ),
                (
                    "meeting_time",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Horaire de réunion"
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministries",
                        to="communities.community",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ministries_led",
                        to="communities.leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ministère",
                "verbose_name_plural": "Ministères",
                "ordering": ["name"],
                "unique_together": {("community", "name")},
            },
        ),
        migrations.CreateModel(
            name="MinistryActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Activité")),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="communities.ministry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité de ministère",
                "verbose_name_plural": "Activités de ministère",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Pastor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("title", models.CharField(max_length=100, verbose_name="Titre")),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("bio", models.TextField(verbose_name="Biographie")),
                (
                    "experience_years",
                    models.PositiveIntegerField(verbose_name="Années d'expérience"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pastors/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="URL externe pour l'image", null=True
                    ),
                ),
                (
                    "is_principal",
                    models.BooleanField(
                        default=False, verbose_name="Pasteur principal"
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastors",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pasteur",
                "verbose_name_plural": "Pasteurs",
                "ordering": ["-is_principal", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ReadingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "participants_count",
                    models.PositiveIntegerField(default=0, verbose_name="Participants"),
                ),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Progression (%)",
                    ),
                ),
                (
                    "current_book",
                    models.CharField(max_length=100, verbose_name="Livre actuel"),
                ),
                (
                    "weekly_reading",
                    models.CharField(
                        max_length=200, verbose_name="Lecture hebdomadaire"
                    ),
                ),
                (
                    "next_milestone",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Prochaine étape"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_programs",
                        to="communities.community",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reading_programs",
                        to="communities.leader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme de lecture",
                "verbose_name_plural": "Programmes de lecture",
            },
        ),
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author_name",
                    models.CharField(max_length=100, verbose_name="Auteur"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("healing", "Guérison"),
                            ("provision", "Provision"),
                            ("salvation", "Salut"),
                            ("deliverance", "Délivrance"),
                            ("relationship", "Relations"),
                            ("professional", "Professionnel"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("excerpt", models.TextField(max_length=500, verbose_name="Extrait")),
                ("full_content", models.TextField(verbose_name="Contenu complet")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonies",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BaptismStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Année")),
                ("count", models.PositiveIntegerField(verbose_name="Nombre")),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baptism_statistics",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique de baptême",
                "verbose_name_plural": "Statistiques de baptême",
                "ordering": ["-year"],
                "unique_together": {("community", "year")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "country")},
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "attended",
                    models.BooleanField(default=False, verbose_name="A participé"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="communities.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to="communities.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription à l'événement",
                "verbose_name_plural": "Inscriptions aux événements",
                "unique_together": {("event", "member")},
            },
        ),
        migrations.CreateModel(
            name="MemberMinistryParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(blank=True, max_length=100, verbose_name="Rôle"),
                ),
                ("join_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministry_participations",
                        to="communities.member",
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_participations",
                        to="communities.ministry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation au ministère",
                "verbose_name_plural": "Participations aux ministères",
                "unique_together": {("member", "ministry")},
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Lundi"),
                            (2, "Mardi"),
                            (3, "Mercredi"),
                            (4, "Jeudi"),
                            (5, "Vendredi"),
                            (6, "Samedi"),
                            (7, "Dimanche"),
                        ],
                        verbose_name="Jour",
                    ),
                ),
                ("time", models.TimeField(verbose_name="Heure")),
                (
                    "type",
                    models.CharField(max_length=100, verbose_name="Type de service"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["day", "time"],
                "unique_together": {("community", "day", "time")},
            },
        ),
    ]
